[General]
# fFarDistance is the far plane distance where the ocean will be culled. Above 2M can introduce artifacting
fFarDistance=2000000.0
# fWaterSkirtRadius is the radius of the the water that is visible. This is culled to 90% of the far plane distance when needed
fWaterSkirtRadius=2000000.0
# fWaterSkirtZOffset is the offset of the water skirt from the ocean height. You can reduce this to hide z-fighting at the cost of a slightly lower horizon.
fWaterSkirtZOffset=-10000.0F